name: üîç Test File Watcher

on:
  workflow_dispatch:   # So you can trigger it manually from GitHub UI

jobs:
  test:
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/check-for-files-changed-v2.yml@main
    with:
      watched_files: |
        .github/workflows/**
        src/**
      # optionally override tags if you want to simulate specific ones
      current_tag:  v1.4.0
      previous_tag: v1.3.1
