name: Build JAR on Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile Java
        run: |
         mkdir -p out
         javac -d out oneProjectWed/src/java/com/miha/app/App.java
    
      - name: Create Manifest
        run: |
          echo "Main-Class: com.miha.app.App" > out/MANIFEST.MF
    
      - name: Package JAR
        run: |
          cd out
          jar cfm App.jar MANIFEST.MF com/miha/app/*.class

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/App.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
