name: Detect File Change + MS Teams Notification

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      watched_file:
        description: "File to watch"
        required: true
        type: string
        default: "oneProjectWed/src/java/com/miha/app/App.java"

jobs:

  check_changes:
    name: Check File Changes
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/3check-file-changes.yml@main
    with:
      watched_files: ${{ github.event.inputs.watched_file || 'oneProjectWed/src/java/com/miha/app/App.java' }}
      current_tag: ${{ github.ref_name }}
      previous_tag: ''   # auto-detects previous tag if your workflow supports it

  notify_if_changed:
    name: Notify MS Teams
    needs: check_changes
    if: needs.check_changes.outputs.files_changed == 'true'
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/teams-notifier.yml@main
    with:
      notification_title: "ðŸ”¥ Important File Changed"
      action_required_message: "File ${{ needs.check_changes.outputs.changed_files_list }} was modified"
      card_color: "FFA500"
