name: Detect Setup Script

on:
  workflow_call:

jobs:
  detect-iss:
    runs-on: ubuntu-latest
    outputs:
      setup_script: ${{ steps.detect.outputs.script }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect .iss setup script
        id: detect
        run: |
          file=$(ls *.iss 2>/dev/null | head -n 1)
          if [ -z "$file" ]; then
            echo "âŒ No .iss setup script found!"
            exit 1
          fi
          echo "Found setup script: $file"
          echo "script=$file" >> $GITHUB_OUTPUT
