name: Notify App Changes

on:
  push:
    paths:
      - '**/src/**/com/miha/app/**'
  workflow_dispatch:

jobs:
  notify:
    uses: ./.github/workflows/teams-notif-on-update.yml
    with:
      # file_path: '**/src/**/com/miha/app/**'
      notification_title: 'üöÄ App Source Files Updated'
      action_required_message: '‚ö†Ô∏è **Action Required:** New installer needs to be prepared for Template Designer'
      card_color: 'Accent'
      show_files: true
   #   teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
    secrets:
     teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
